config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'pages#home'
  resources :blogs, only: [:new, :create, :index, :delete]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 600 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def signed_in_only!
    # current_user in ApplicationController must be defined as helper method to make it work
    redirect_to new_user_session_path unless current_user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :signed_in_only!, only: %i[new create]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show; end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit; end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = current_user.blogs.build(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blogs_path, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<div class='container'>
  
    <% if blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

        <ul>
          <% blog.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class='row justify-content-center'>
      <div class='col-10'>
        <%= form_with(model: blog, class: 'shadow-lg p-3 mb-3 form-bg rounded', local: true) do |form| %>
        <div class='form-group row'>
          <%= form.label :title, class: 'text-white col-2 col-form-label'%>
          <div class='col-10'>
            <%= form.text_field :title, class: 'form-control rounded', placeholder: "Title of article" %>
          </div>
        </div>

        <div class='form-group row'> 
          <%= form.label :descripion, class: 'text-white col-2 col-form-label' %>
          <div class='col-10'>
            <%= form.text_area :description, rows: 10, class: 'form-control rounded', placeholder: "Description of article"%>
          </div>
        </div>

        <div class="actions form-group row justify-content-center">
          <%= form.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <%= link_to '[ Cancel and return to articles listing ]', blogs_path, class: 'text-white'%>
  </div>
</div>

app/views/blogs/edit.html.erb
<h2 class='text-center'>Create new Article</h2>

<%= render 'form', blog: @blog %>
<%= link_to 'Show', @blog %> |

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<h2 class='text-center'>All articles</h2>
<div class='container'>
  <% @blogs.each do |blog| %>
    <div class='row justify-content-md-center'>
      <div class='col-8 mt-4'>
        <div class="card text-center shadow-lg mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if user_signed_in? %>
           <p> created by <%= blog.user.username %>
            <% else %>
              <%= link_to 'Sign up', new_user_registration_path, class: 'text-white'%> to see the blogers 
            <% end %>
          </div>
          <div class="card-body card-body-color">
            <h5 class="card-title"><%= link_to blog.title, blogs_path(blog), class: 'text-light' %></h5>
            <p class="card-text"><%= truncate(blog.description, length: 50) %></p>           
          <div class="card-footer">
            <small> Created <%= time_ago_in_words(blog.created_at) %> ago,
            updated <%= time_ago_in_words(blog.updated_at) %> ago,
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/blogs/new.html.erb
<h2 class='text-center'>Create new Article</h2>

<%= render 'form', blog: @blog %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<h2 class='text-center'><%= @blog.title %> </h2>
<div class='container'>
  <div class='row justify-content-md-center'>
  <div class='col-8 mt-4'>
        <div class="card text-center shadow-lg mb-5 bg-white rounded">
          <div class="card-header font-italic">
              <% if user_signed_in? %>
                created by <%= current_user.username %>
              <% else %>
                <%= link_to 'Sign up', new_user_registration_path, class: 'text-white'%> to see the blogers 
              <% end %>
          </div>
          <div class="card-body card-body-color">
            <p class="card-text"><%= @blog.description %></p>
            <% if user_signed_in? %>           
              <%= link_to 'Edit', edit_blog_path(@blog), class: 'btn btn-warning'%>
              <%= link_to "Delete", blog_path(@blog), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer">
            <small> Created <%= time_ago_in_words(@blog.created_at) %> ago,
            updated <%= time_ago_in_words(@blog.updated_at) %> ago,
            </small>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; Your Website</small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<p class="alert"><%= alert %></p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-color navbar-expand-lg navbar-light bg-light">
  <%= link_to 'WOG', root_path, class: 'navbar-brand bold', id: 'logo'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to 'Articles listing', blogs_path, class: 'nav-link text-white'%>
      <%= link_to 'Create new article', new_blog_path, class: 'nav-link text-white'%>
      <% if user_signed_in? %>
        <p class='control'>
          <%= link_to current_user.name, edit_user_registration_path, class: 'nav-link text-white font-italic'%>
        </p>
        <p>
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link text-white'%>
        </p>
      <% else %>
        <p class='control'>
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link text-white'%>
        </p>
        <p class='control'>
          <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link text-white'%>
        </p>

      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthenticationProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation'%>
    <div id="page-content">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/home.html.erb
<div class='container'>
  <div class="jumbotron text-center text">
    <h1 class="display-4">Hello, world!</h1>
    <p class="lead">WordPress is open source software you can use to create a beautiful website, blog, or app.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <a class="btn btn-light btn-lg" href="#" role="button">Learn more</a>
  </div>
</div>

<div id="page-content">

</div>